esphome:
  name: higrow
  comment: Flower monitor
  on_boot:
    then:
      - deep_sleep.prevent: deep_sleep_control

esp32:
  board: lolin32
  framework:
    type: arduino

api:

ota:
  password: ""


wifi:
  ssid: "SSID"
  password: "PASSWORD"
  fast_connect: true
  power_save_mode: high
  manual_ip:
    static_ip: 192.168.0.110
    gateway: 192.168.1.1
    subnet: 255.255.255.0
  
i2c:
  sda: 25
  scl: 26
  scan: False
  id: bus_a
  setup_priority: -200

deep_sleep:
  id: deep_sleep_control
  run_duration: 10s
  sleep_duration: 3600s
  setup_priority: -300


# Sensor power control pin , use detected must set high
switch:
  - platform: gpio
    pin: GPIO4
    name: "Sensor Power"
    id: spower
    restore_mode: ALWAYS_ON
    internal: true
    setup_priority: 1000

sensor:
  - platform: adc
    pin: 34
    name: "HiGrow Salt"
    device_class: humidity
    attenuation: 11db
    update_interval: 60s
    unit_of_measurement: '%'
    filters:
      - calibrate_linear:
          - 0.06 -> 0.0
          - 1.8 -> 100.0
  - platform: adc
    pin: 32
    name: "HiGrow Soil"
    device_class: humidity
    update_interval: 60s
    attenuation: 11db
    unit_of_measurement: '%'
    filters:
      - calibrate_linear:
          - 2.6 -> 0.0
          - 1.2 -> 100.0
      # - lambda: return max(double(x), 0.00);
  - platform: adc
    pin: 33
    name: "voltage"
    id: "higrow_voltage"
    attenuation: 11db
    unit_of_measurement: 'V'
    update_interval: 60s
    filters:
      - calibrate_linear:
          - 0.0 -> 0.0
          - 2.06 -> 1.89
      - lambda: return x * 2.0;

  - platform: template
    name: "battery_level"
    device_class: battery
    state_class: measurement
    setup_priority: -200
    unit_of_measurement: '%'
    update_interval: 60s
    accuracy_decimals: 0

    lambda: |-
      int val = round((((id(higrow_voltage).state - 2.70) / 0.98) * 100.00));
      return max(min(val, 100), 0);
  - platform: bh1750
    name: "BH1750 Illuminance"
    address: 0x23
    update_interval: 60s
    setup_priority: -200
  - platform: bme280
    temperature:
      name: "BME280 Temperature"
      oversampling: 16x
    pressure:
      name: "BME280 Pressure"
    humidity:
      name: "BME280 Humidity"
    address: 0x77
    update_interval: 60s
    setup_priority: -200

binary_sensor:
  - platform: template
    id: "is_charging"
    name: "Charging"
    device_class: "battery_charging"
    lambda: |-
      if (id(higrow_voltage).state > 4.0) {
        return true;
      } else {
        return false;
      }
    on_press: 
      then:
        - logger.log: 'stop deep sleep'
        - deep_sleep.prevent: deep_sleep_control
    on_release:
      then:
        - logger.log: 'allow deep sleep'
        - deep_sleep.allow: deep_sleep_control